### PR TITLE
Local 82

### PR DESCRIPTION
**Pull request by phax**
The branch for #82

### CODE REVIEW

**Comment by guiguilechat** [comment]
is it working ? Did not test.
No issue with licensing ?

**Comment by phax** [comment]
It works for me. I don't see an issue with licensing, as it only uses runtime stuff. Or do you have anything particular in mind?

**Comment by guiguilechat** [comment]
Nothing in mind, just asking in case you had.

**Comment by guiguilechat** [comment]
"it works" as "the tests I designed a year ago have passed" or "your own test have passed" ?

**Comment by phax** [comment]
I assume you agree that the code you provided can be re-published under the projects license :)

**Comment by guiguilechat** [comment]
Of course, I just took several parts of code and it's up to you to do what you want with it.

**Comment by phax** [comment]
I added some tests and in general it looks good.
Errors are detected as errors, and valid ones just do what they are supposed to do.
The future extensions are pretty clear - write to disk optional etc.

**Pull request merged**
